### ISSUE TITLE
Validate and adapt pipelines with exports

### ISSUE THREAD

**Issue by dietzc** [CellProfiler/knime-bridge#5]
@LeeKamentsky would it make sense, that on CellProfiler side Modules like "Save Images" or "Export to Spreadsheet" are automatically removed from the pipeline when called from KNIME?

**Comment by LeeKamentsky** [comment]
It might be nice to have as part of the API, "Clean up this pipeline for
me". Then you could choose whether you wanted to do something stupid or
not. Eventually, I think we want SaveImages to be an indicator of an image
or segmentation output. Does that work? I would like to have an API that
let you programatically manipulate a pipeline - something that would let
you find the modules and settings, validate that the pipeline works, and
change setting values. There are a lot of people who want to investigate a
parameter space - run a short set of images with setting A, B and C and see
which does best and a programatic pipeline editor would do what they want.

**Comment by dietzc** [comment]
It would be amazing if you could get additional information as Images or Labelings in KNIME. We could add functions for `getImageNames()` and `getImage(IImgDescriptor descriptor)`.

**Comment by dietzc** [comment]
As I'm back working on the KNIME CellProfiler Integration: I really like the idea to have a function: `cleanUpPipeline(boolean doCleanUp)` (or so) which removes all modules which cause errors in the KNIME Integration. Later, we could add the functionality, that images and labelings can also be returned to KNIME.

**Comment by LeeKamentsky** [comment]
For server-side see https://github.com/CellProfiler/CellProfiler/commit/629563aaf5ca0d70aa7b6dbd1522db1536fa504e

You probably want to call IKnimeBridge.cleanPipeline(void) although there are a myriad of choices available to you.

**Comment by dietzc** [comment]
Oh wow. Great! Thanks Lee!! I will try it!!

**Comment by dietzc** [comment]
@LeeKamentsky 

Do I have to do more than: Pulling latest CellProfiler master, updating the KNIME-Bridge in knip-cellprofiler and call `cleanUpPipeline()` after loading the pipeline?

I'm getting an exception:  `Unexpected cellprofiler exception` which actually is a ProtocolException (message not supported). The message from CellProfiler is `[ 6d843ffa-e9d4-4daf-bba5-0143232c92c9, , cellprofiler-exception-1, Unhandled message type: clean-pipeline-request-1 ]`

**Comment by dietzc** [comment]
found it and I will fix it

**Comment by dietzc** [comment]
Unfortunately another issue: The `String` of the pipeline which is set after `cleanUpPipeline()` was called looks as follows: "26967477261790A2020202052656C617469766520776569676874206F662074686520726564206368616E6E656C3A310A2020202052656C617469766520776569676874206F662074686520677265656E206368616E6E656C3A310A2020202052656C617469766520776569676874206F662074686520626C7565206368616E6E656C3A310A20202020436F6E766572742072656420746F20677261793F3A4E6F0A202020204E616D6520746865206F757470757420696D6167653A4F7269675265640A20202020436F6E7665727 ... etc" and therefore can't be executed anymore.

**Comment by LeeKamentsky** [comment]
I realized that, although I wrote tests for the server and client side, I never tried the two of them together. I'll fix this this morning.

**Comment by dietzc** [comment]
Ah great! Thanks. I think the problem with the "String" is related to special characters in the pipeline.

**Comment by dietzc** [comment]
problem related to '\n' & co. this guy kills our string.

**Comment by LeeKamentsky** [comment]
OK - I checked in https://github.com/CellProfiler/CellProfiler/commit/5e7f222fc636ff08148946b73ed602f090d8b5a7 which should fix the server side and I wrote a unit test for linefeeds in pipelines which appropriately failed, then found out that msg.popString() gracefully converts a message to hex if there is a linefeed in it which is, I suppose, what you should expect. I've replaced every call to msg.popString with AbstractReply.popString() which decants the byte data and encodes it as a UTF-8 string.

**Comment by dietzc** [comment]
Ok! I will revert https://github.com/CellProfiler/knime-bridge/commit/7efdcb54acac2e94627c8939a6c166b5323029f8 then.

Thanks for fixing so fast @LeeKamentsky !! +1

**Comment by dietzc** [comment]
my maven build fails with:
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/RunReq.java: Some input files use or override a deprecated API.
[WARNING] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/RunReq.java: Recompile with -Xlint:deprecation for details.
[INFO] 2 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/AbstractReply.java:[12,37] package org.python.google.common.base does not exist
[ERROR] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/CleanPipelineReply.java:[11,37] package org.python.google.common.base does not exist
[ERROR] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/AbstractReply.java:[12,37] package org.python.google.common.base does not exist
[ERROR] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/CleanPipelineReply.java:[11,37] package org.python.google.common.base does not exist
[ERROR] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/AbstractReply.java:[103,56] cannot find symbol
  symbol:   variable Charsets
  location: class org.cellprofiler.knimebridge.message.AbstractReply
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.770s
[INFO] Finished at: Fri Feb 20 17:15:47 CET 2015
[INFO] Final Memory: 146M/860M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project knime-bridge: Compilation failure: Compilation failure:
[ERROR] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/AbstractReply.java:[12,37] package org.python.google.common.base does not exist
[ERROR] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/CleanPipelineReply.java:[11,37] package org.python.google.common.base does not exist
[ERROR] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/AbstractReply.java:[12,37] package org.python.google.common.base does not exist
[ERROR] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/CleanPipelineReply.java:[11,37] package org.python.google.common.base does not exist
[ERROR] /home/dietzc/devel/git-repositories/knime-bridge/src/main/java/org/cellprofiler/knimebridge/message/AbstractReply.java:[103,56] cannot find symbol

**Comment by LeeKamentsky** [comment]
sorry about that, try 7664a32
Eclipse magically picked out Charsets.UTF_8 for me and I was so happy I didn't realize it was using some random library that's not in the POM. Replaced it with "UTF-8".

**Comment by dietzc** [comment]
great! thanks!
